version: "3"

networks:
  tube_net:
    driver: bridge


services:
  
  web:
    container_name: web_server
    build:
      context: ./django_dir
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    networks:
      - tube_net

  question_server:
    container_name: question_server
    build:
      context: ./question_server
      dockerfile: dockerfile
    volumes:
      - ./question_server/question_server/yaml_questions/:/app/question_server_yaml
    networks:
      - tube_net
