# syntax=docker/dockerfile:1.4

FROM --platform=$BUILDPLATFORM python:3.10-alpine AS builder
EXPOSE 8756
WORKDIR /app 
COPY requirements.txt /app
RUN pip3 install -r requirements.txt --no-cache-dir
COPY . /app 
USER daemon
ENTRYPOINT ["python3"] 
CMD ["manage.py", "runserver", "0.0.0.0:8756"]