# syntax=docker/dockerfile:1.4

FROM --platform=$BUILDPLATFORM python:3.10-alpine AS builder
EXPOSE 8756
WORKDIR /app 
COPY requirements.txt /app
RUN pip3 install -r requirements.txt --no-cache-dir
COPY . /app

RUN chown -R daemon /app 
USER daemon
# ENTRYPOINT ["python3"] 

# CMD ["manage.py", "runserver", "0.0.0.0:8756"]
CMD ["sh", "-c", "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py load_questions /app/question_server/yaml_questions && python3 manage.py runserver 0.0.0.0:8756"]