# Generated by Django 5.0.6 on 2024-05-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sim", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizTaker",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=500)),
                ("last_name", models.CharField(max_length=500)),
                (
                    "programming_ability",
                    models.CharField(
                        choices=[
                            ("NOCD", "No Coding Experience"),
                            ("BGNR", "Beginner"),
                            ("INTR", "Intermediate"),
                            ("ADVD", "Advanced"),
                        ],
                        default="BGNR",
                        max_length=4,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CategoryTag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("tags", models.ManyToManyField(to="sim.question")),
            ],
        ),
    ]
